site_name: Универкон - Система управления образовательной организацией

dev_addr: 127.0.0.1:8000
# Настройки LiveReload
extra:
  live_reload: true
  reload_delay: 500  # задержка в миллисекундах
  dirty_reload: true

theme:
  name: material
  language: ru
  logo: assets/images/favicon/favicon.ico

  # Настройки favicon
  favicon: assets/images/favicon/favicon.ico
  
  palette:
    - scheme: slate
      primary: teal
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: Переключить на светлую тему
    - scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/weather-night
        name: Переключить на тёмную тему

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

repo_url: https://github.com/iMironRU/framework.univercon.aplicon.ru
repo_name: iMironRU/framework.univercon.aplicon.ru
edit_uri: edit/main/docs/

# ИСКЛЮЧАЕМ README.md ИЗ СБОРКИ
exclude_docs: |
  README.md

extra_javascript:
  - javascripts/glossary-data.js
  - javascripts/tooltips.js
  - javascripts/contribute.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/mermaid.css
#  - stylesheets/table_exporter.css



plugins:  
  - search
  - git-committers:
      repository: iMironRU/framework.univercon.aplicon.ru
      branch: main
      token: !ENV ${SECRET_KEY}
  - git-revision-date-localized:
      enable_creation_date: true
  - macros
  - mermaid2
  - bpmn-js:
      viewer_js: "https://unpkg.com/bpmn-js@18/dist/bpmn-navigated-viewer.production.min.js"
      viewer_css: "https://unpkg.com/bpmn-js@18/dist/assets/bpmn-js.css"
      class: "mk-bpmn-js"
  - markmap


#plugins-dirs: ['plugins']

extra:
  footer:
    - Секция 1:
      - Copyright © 2022 - 2025 https://framework.aplicon.ru
    - Секция 2:
      - Документация:
      - Начало работы - /getting-started/
nav:
- Главная: index.md
- Управление: 
  - Обзор управления: management/index.md
  - Виды образования в Российской Федерации: management/TypesOfEducation.md
  - Организационная структура:
    - Структура организации: management/structure.md
    - Штатное расписание: management/edu_org_staffing.md
    - Должностные инструкции: management/positions.md
  - Политики и регламенты:
    - Внутренние регламенты: management/policies.md
    - Локальные акты: management/local_acts.md
  - Законодательная база: management/legislation.md
  
- Планирование:
  - Обзор планирования: planning/index.md
  - Учебные планы:
    - Основные программы: planning/curriculum.md
    - Дополнительные программы: planning/additional_programs.md
  - Календарные графики:
    - Учебный год: planning/schedules.md
    - Каникулярное время: planning/holidays.md
- Контингент обучающихся:
  - Обзор контингента: students/index.md
  - База данных учащихся:
    - Список статусов обучающихся: students/database/list_of_status.md
    - Список видов приказов: students/database/list_of_orders.md
    - Обзор базы данных: students/database/index.md    
    - Архив данных: students/database/archive.md
  - Статистика и отчеты:
    - Текущая статистика: students/statistics.md
    - Аналитические отчеты: students/analytics.md
- Учебный процесс:
  - Обзор учебного процесса: educational-process/index.md
  - Расписания:
    - Занятий: educational-process/schedules.md
    - Экзаменов: educational-process/exam_schedules.md
  - Академическая успеваемость:
    - Ведомости: educational-process/academic-performance.md
    - Рейтинги: educational-process/ratings.md
- Воспитательная деятельность:
  - Обзор воспитательной работы: extracurricular/index.md
  - Мероприятия:
    - Календарь мероприятий: extracurricular/events.md
    - Планы воспитательной работы: extracurricular/plans.md
  - Студенческие объединения:
    - Список объединений: extracurricular/student-organizations.md
    - Руководство объединениями: extracurricular/org_management.md
- Научная деятельность:
  - Обзор научной работы: research/index.md
  - Исследовательские проекты:
    - Текущие проекты: research/projects.md
    - Архив проектов: research/projects_archive.md
  - Публикации:
    - Научные статьи: research/publications.md
    - Монографии: research/monographs.md
- О системе:
  - Введение: about/introduction.md
  - Обзор системы: about/index.md
  - Техническая документация:
    - О фреймворке: about-framework/index.md
    - Техническое описание: about/technical.md
    - API документация: 
      - Обзор: about/api.md
      - Внешние API: 
        #- Список: about/api/ExtAPI
        - API - Отправка документов на подпись в Госключ: about/api/ExtAPI/GosKeyAPI/index.md
      - Внутренние API: about/api/IntAPI
  - Руководство пользователя:
    - Основное руководство: about/user-guide.md
    - Частые вопросы: about/faq.md
  - Глоссарий: glossary.md
# - Инструкция по сборке: read_me_to_build.md
